// Code generated by MockGen. DO NOT EDIT.
// Source: handlers.go

// Package mock_admin is a generated GoMock package.
package mock_admin

import (
	context "context"
	domain "redCollar/internal/domain"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	uuid "github.com/google/uuid"
)

// MockAdminIncidents is a mock of AdminIncidents interface.
type MockAdminIncidents struct {
	ctrl     *gomock.Controller
	recorder *MockAdminIncidentsMockRecorder
}

// MockAdminIncidentsMockRecorder is the mock recorder for MockAdminIncidents.
type MockAdminIncidentsMockRecorder struct {
	mock *MockAdminIncidents
}

// NewMockAdminIncidents creates a new mock instance.
func NewMockAdminIncidents(ctrl *gomock.Controller) *MockAdminIncidents {
	mock := &MockAdminIncidents{ctrl: ctrl}
	mock.recorder = &MockAdminIncidentsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAdminIncidents) EXPECT() *MockAdminIncidentsMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockAdminIncidents) Create(ctx context.Context, req domain.CreateIncidentRequest) (uuid.UUID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, req)
	ret0, _ := ret[0].(uuid.UUID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockAdminIncidentsMockRecorder) Create(ctx, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockAdminIncidents)(nil).Create), ctx, req)
}

// Delete mocks base method.
func (m *MockAdminIncidents) Delete(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockAdminIncidentsMockRecorder) Delete(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockAdminIncidents)(nil).Delete), ctx, id)
}

// Get mocks base method.
func (m *MockAdminIncidents) Get(ctx context.Context, id uuid.UUID) (*domain.Incident, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, id)
	ret0, _ := ret[0].(*domain.Incident)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockAdminIncidentsMockRecorder) Get(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockAdminIncidents)(nil).Get), ctx, id)
}

// List mocks base method.
func (m *MockAdminIncidents) List(ctx context.Context, page, limit int) ([]*domain.Incident, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, page, limit)
	ret0, _ := ret[0].([]*domain.Incident)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// List indicates an expected call of List.
func (mr *MockAdminIncidentsMockRecorder) List(ctx, page, limit interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockAdminIncidents)(nil).List), ctx, page, limit)
}

// Update mocks base method.
func (m *MockAdminIncidents) Update(ctx context.Context, id uuid.UUID, req domain.UpdateIncidentRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, id, req)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockAdminIncidentsMockRecorder) Update(ctx, id, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockAdminIncidents)(nil).Update), ctx, id, req)
}

// MockLocationChecker is a mock of LocationChecker interface.
type MockLocationChecker struct {
	ctrl     *gomock.Controller
	recorder *MockLocationCheckerMockRecorder
}

// MockLocationCheckerMockRecorder is the mock recorder for MockLocationChecker.
type MockLocationCheckerMockRecorder struct {
	mock *MockLocationChecker
}

// NewMockLocationChecker creates a new mock instance.
func NewMockLocationChecker(ctrl *gomock.Controller) *MockLocationChecker {
	mock := &MockLocationChecker{ctrl: ctrl}
	mock.recorder = &MockLocationCheckerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLocationChecker) EXPECT() *MockLocationCheckerMockRecorder {
	return m.recorder
}

// CheckLocation mocks base method.
func (m *MockLocationChecker) CheckLocation(ctx context.Context, req domain.LocationCheckRequest) (domain.LocationCheckResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckLocation", ctx, req)
	ret0, _ := ret[0].(domain.LocationCheckResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckLocation indicates an expected call of CheckLocation.
func (mr *MockLocationCheckerMockRecorder) CheckLocation(ctx, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckLocation", reflect.TypeOf((*MockLocationChecker)(nil).CheckLocation), ctx, req)
}

// MockStatsGetter is a mock of StatsGetter interface.
type MockStatsGetter struct {
	ctrl     *gomock.Controller
	recorder *MockStatsGetterMockRecorder
}

// MockStatsGetterMockRecorder is the mock recorder for MockStatsGetter.
type MockStatsGetterMockRecorder struct {
	mock *MockStatsGetter
}

// NewMockStatsGetter creates a new mock instance.
func NewMockStatsGetter(ctrl *gomock.Controller) *MockStatsGetter {
	mock := &MockStatsGetter{ctrl: ctrl}
	mock.recorder = &MockStatsGetterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStatsGetter) EXPECT() *MockStatsGetterMockRecorder {
	return m.recorder
}

// GetStats mocks base method.
func (m *MockStatsGetter) GetStats(ctx context.Context, req domain.StatsRequest) (*domain.IncidentStats, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStats", ctx, req)
	ret0, _ := ret[0].(*domain.IncidentStats)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStats indicates an expected call of GetStats.
func (mr *MockStatsGetterMockRecorder) GetStats(ctx, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStats", reflect.TypeOf((*MockStatsGetter)(nil).GetStats), ctx, req)
}
