// Code generated by MockGen. DO NOT EDIT.
// Source: handlers.go

// Package mock_public is a generated GoMock package.
package mock_public

import (
	context "context"
	domain "redCollar/internal/domain"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockPublicHandler is a mock of PublicHandler interface.
type MockPublicHandler struct {
	ctrl     *gomock.Controller
	recorder *MockPublicHandlerMockRecorder
}

// MockPublicHandlerMockRecorder is the mock recorder for MockPublicHandler.
type MockPublicHandlerMockRecorder struct {
	mock *MockPublicHandler
}

// NewMockPublicHandler creates a new mock instance.
func NewMockPublicHandler(ctrl *gomock.Controller) *MockPublicHandler {
	mock := &MockPublicHandler{ctrl: ctrl}
	mock.recorder = &MockPublicHandlerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPublicHandler) EXPECT() *MockPublicHandlerMockRecorder {
	return m.recorder
}

// CheckLocation mocks base method.
func (m *MockPublicHandler) CheckLocation(ctx context.Context, req domain.LocationCheckRequest) (domain.LocationCheckResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckLocation", ctx, req)
	ret0, _ := ret[0].(domain.LocationCheckResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckLocation indicates an expected call of CheckLocation.
func (mr *MockPublicHandlerMockRecorder) CheckLocation(ctx, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckLocation", reflect.TypeOf((*MockPublicHandler)(nil).CheckLocation), ctx, req)
}
