// Code generated by MockGen. DO NOT EDIT.
// Source: service.go

// Package mock_service is a generated GoMock package.
package mock_service

import (
	context "context"
	domain "redCollar/internal/domain"
	reflect "reflect"
	time "time"

	gomock "github.com/golang/mock/gomock"
	uuid "github.com/google/uuid"
)

// MockAdminIncidentService is a mock of AdminIncidentService interface.
type MockAdminIncidentService struct {
	ctrl     *gomock.Controller
	recorder *MockAdminIncidentServiceMockRecorder
}

// MockAdminIncidentServiceMockRecorder is the mock recorder for MockAdminIncidentService.
type MockAdminIncidentServiceMockRecorder struct {
	mock *MockAdminIncidentService
}

// NewMockAdminIncidentService creates a new mock instance.
func NewMockAdminIncidentService(ctrl *gomock.Controller) *MockAdminIncidentService {
	mock := &MockAdminIncidentService{ctrl: ctrl}
	mock.recorder = &MockAdminIncidentServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAdminIncidentService) EXPECT() *MockAdminIncidentServiceMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockAdminIncidentService) Create(ctx context.Context, req domain.CreateIncidentRequest) (uuid.UUID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, req)
	ret0, _ := ret[0].(uuid.UUID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockAdminIncidentServiceMockRecorder) Create(ctx, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockAdminIncidentService)(nil).Create), ctx, req)
}

// Delete mocks base method.
func (m *MockAdminIncidentService) Delete(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockAdminIncidentServiceMockRecorder) Delete(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockAdminIncidentService)(nil).Delete), ctx, id)
}

// Get mocks base method.
func (m *MockAdminIncidentService) Get(ctx context.Context, id uuid.UUID) (*domain.Incident, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, id)
	ret0, _ := ret[0].(*domain.Incident)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockAdminIncidentServiceMockRecorder) Get(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockAdminIncidentService)(nil).Get), ctx, id)
}

// List mocks base method.
func (m *MockAdminIncidentService) List(ctx context.Context, page, limit int) ([]*domain.Incident, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, page, limit)
	ret0, _ := ret[0].([]*domain.Incident)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// List indicates an expected call of List.
func (mr *MockAdminIncidentServiceMockRecorder) List(ctx, page, limit interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockAdminIncidentService)(nil).List), ctx, page, limit)
}

// Update mocks base method.
func (m *MockAdminIncidentService) Update(ctx context.Context, id uuid.UUID, req domain.UpdateIncidentRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, id, req)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockAdminIncidentServiceMockRecorder) Update(ctx, id, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockAdminIncidentService)(nil).Update), ctx, id, req)
}

// MockIncidentRepository is a mock of IncidentRepository interface.
type MockIncidentRepository struct {
	ctrl     *gomock.Controller
	recorder *MockIncidentRepositoryMockRecorder
}

// MockIncidentRepositoryMockRecorder is the mock recorder for MockIncidentRepository.
type MockIncidentRepositoryMockRecorder struct {
	mock *MockIncidentRepository
}

// NewMockIncidentRepository creates a new mock instance.
func NewMockIncidentRepository(ctrl *gomock.Controller) *MockIncidentRepository {
	mock := &MockIncidentRepository{ctrl: ctrl}
	mock.recorder = &MockIncidentRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIncidentRepository) EXPECT() *MockIncidentRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockIncidentRepository) Create(ctx context.Context, incident *domain.Incident) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, incident)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockIncidentRepositoryMockRecorder) Create(ctx, incident interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockIncidentRepository)(nil).Create), ctx, incident)
}

// Delete mocks base method.
func (m *MockIncidentRepository) Delete(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockIncidentRepositoryMockRecorder) Delete(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockIncidentRepository)(nil).Delete), ctx, id)
}

// Get mocks base method.
func (m *MockIncidentRepository) Get(ctx context.Context, id uuid.UUID) (*domain.Incident, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, id)
	ret0, _ := ret[0].(*domain.Incident)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockIncidentRepositoryMockRecorder) Get(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockIncidentRepository)(nil).Get), ctx, id)
}

// List mocks base method.
func (m *MockIncidentRepository) List(ctx context.Context, page, limit int) ([]*domain.Incident, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, page, limit)
	ret0, _ := ret[0].([]*domain.Incident)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// List indicates an expected call of List.
func (mr *MockIncidentRepositoryMockRecorder) List(ctx, page, limit interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockIncidentRepository)(nil).List), ctx, page, limit)
}

// ListActive mocks base method.
func (m *MockIncidentRepository) ListActive(ctx context.Context) ([]*domain.Incident, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListActive", ctx)
	ret0, _ := ret[0].([]*domain.Incident)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListActive indicates an expected call of ListActive.
func (mr *MockIncidentRepositoryMockRecorder) ListActive(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListActive", reflect.TypeOf((*MockIncidentRepository)(nil).ListActive), ctx)
}

// Update mocks base method.
func (m *MockIncidentRepository) Update(ctx context.Context, incident *domain.Incident) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, incident)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockIncidentRepositoryMockRecorder) Update(ctx, incident interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockIncidentRepository)(nil).Update), ctx, incident)
}

// MockIncidentCacheService is a mock of IncidentCacheService interface.
type MockIncidentCacheService struct {
	ctrl     *gomock.Controller
	recorder *MockIncidentCacheServiceMockRecorder
}

// MockIncidentCacheServiceMockRecorder is the mock recorder for MockIncidentCacheService.
type MockIncidentCacheServiceMockRecorder struct {
	mock *MockIncidentCacheService
}

// NewMockIncidentCacheService creates a new mock instance.
func NewMockIncidentCacheService(ctrl *gomock.Controller) *MockIncidentCacheService {
	mock := &MockIncidentCacheService{ctrl: ctrl}
	mock.recorder = &MockIncidentCacheServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIncidentCacheService) EXPECT() *MockIncidentCacheServiceMockRecorder {
	return m.recorder
}

// GetActive mocks base method.
func (m *MockIncidentCacheService) GetActive(ctx context.Context) ([]domain.CachedIncident, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetActive", ctx)
	ret0, _ := ret[0].([]domain.CachedIncident)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetActive indicates an expected call of GetActive.
func (mr *MockIncidentCacheServiceMockRecorder) GetActive(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetActive", reflect.TypeOf((*MockIncidentCacheService)(nil).GetActive), ctx)
}

// SetActive mocks base method.
func (m *MockIncidentCacheService) SetActive(ctx context.Context, incidents []domain.CachedIncident, ttl time.Duration) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetActive", ctx, incidents, ttl)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetActive indicates an expected call of SetActive.
func (mr *MockIncidentCacheServiceMockRecorder) SetActive(ctx, incidents, ttl interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetActive", reflect.TypeOf((*MockIncidentCacheService)(nil).SetActive), ctx, incidents, ttl)
}

// MockPublicIncidentService is a mock of PublicIncidentService interface.
type MockPublicIncidentService struct {
	ctrl     *gomock.Controller
	recorder *MockPublicIncidentServiceMockRecorder
}

// MockPublicIncidentServiceMockRecorder is the mock recorder for MockPublicIncidentService.
type MockPublicIncidentServiceMockRecorder struct {
	mock *MockPublicIncidentService
}

// NewMockPublicIncidentService creates a new mock instance.
func NewMockPublicIncidentService(ctrl *gomock.Controller) *MockPublicIncidentService {
	mock := &MockPublicIncidentService{ctrl: ctrl}
	mock.recorder = &MockPublicIncidentServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPublicIncidentService) EXPECT() *MockPublicIncidentServiceMockRecorder {
	return m.recorder
}

// CheckLocation mocks base method.
func (m *MockPublicIncidentService) CheckLocation(ctx context.Context, req domain.LocationCheckRequest) (domain.LocationCheckResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckLocation", ctx, req)
	ret0, _ := ret[0].(domain.LocationCheckResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckLocation indicates an expected call of CheckLocation.
func (mr *MockPublicIncidentServiceMockRecorder) CheckLocation(ctx, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckLocation", reflect.TypeOf((*MockPublicIncidentService)(nil).CheckLocation), ctx, req)
}

// MockStatsService is a mock of StatsService interface.
type MockStatsService struct {
	ctrl     *gomock.Controller
	recorder *MockStatsServiceMockRecorder
}

// MockStatsServiceMockRecorder is the mock recorder for MockStatsService.
type MockStatsServiceMockRecorder struct {
	mock *MockStatsService
}

// NewMockStatsService creates a new mock instance.
func NewMockStatsService(ctrl *gomock.Controller) *MockStatsService {
	mock := &MockStatsService{ctrl: ctrl}
	mock.recorder = &MockStatsServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStatsService) EXPECT() *MockStatsServiceMockRecorder {
	return m.recorder
}

// GetStats mocks base method.
func (m *MockStatsService) GetStats(ctx context.Context, req domain.StatsRequest) (*domain.IncidentStats, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStats", ctx, req)
	ret0, _ := ret[0].(*domain.IncidentStats)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStats indicates an expected call of GetStats.
func (mr *MockStatsServiceMockRecorder) GetStats(ctx, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStats", reflect.TypeOf((*MockStatsService)(nil).GetStats), ctx, req)
}
